version: 2.1
executors:
  default:
    machine:
      image: ubuntu-1604:202004-01
  
jobs:
  install_rust:
    executor: default
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --profile default
  checkout:
    executor: default
    steps:
      - checkout
      - run: cargo fetch
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .cargo/registry
            - .cargo/git
  clippy:
    executor: default
    steps:
      - attach_workspace:
          at: .cargo/
      - run: cargo clippy --all --all-targets -- -Dwarnings -Drust-2018-idioms
  test:
    executor: default
    steps:
      - attach_workspace:
          at: .cargo/
      - restore_cache:
          key: cargo-lock-{{ checksum Cargo.lock }}
      - run: cargo test
      - save_cache:
          key: cargo-lock-{{ checksum Cargo.lock }}
          paths:
            - target/
  fmt:
    executor: default
    steps:
      - attach_workspace:
          at: .cargo/
      - run: cargo fmt --all -- --check

workflows:
  lint_and_test:
    jobs:
      - install_rust
      - checkout:
          requires: [install_rust]
      - fmt:
          requires: [checkout]
      - clippy:
          requires: [checkout]
      - test:
          requires: [checkout]
