version: 2.1
executors:
  default:
    machine:
      image: ubuntu-1604:202004-01
  
jobs:
  install_rust_and_checkout:
    executor: default
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --profile default
      - checkout
      - run: |
         source /home/circleci/.cargo/env
         cargo update
         cargo fetch
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .cargo/
            - .rustup/
            - project/
  clippy:
    executor: default
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: |
          source /home/circleci/.cargo/env
          cargo clippy --all --all-targets -- -Dwarnings -Drust-2018-idioms
  test:
    executor: default
    steps:
      - attach_workspace:
          at: /home/circleci
      - restore_cache:
          key: cargo-lock-
      - run: |
          source /home/circleci/.cargo/env
          cargo test
      - save_cache:
          key: cargo-lock-{{ epoch }}
          paths:
            - target/
  fmt:
    executor: default
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: |
          source /home/circleci/.cargo/env
          cargo fmt --all -- --check

workflows:
  lint_and_test:
    jobs:
      - install_rust_and_checkout
      - fmt:
          requires: [install_rust_and_checkout]
      - clippy:
          requires: [install_rust_and_checkout]
      - test:
          requires: [install_rust_and_checkout]
